### ISSUE TITLE
Name confusingly similar to Internet Relay Chat

### ISSUE THREAD

**Issue by janicez** [Ronsor/relaychat#1]
This isn't IRC but has basically the same name

**Comment by Ronsor** [comment]
It is a relay chat

**Comment by janicez** [comment]
It's not IRC, though, and IRC is "Internet Relay Chat." Either this doesn't run over internet protocols (it does) or rename it (say, to RRC)

**Comment by Ronsor** [comment]
We are now known as Ronsor Relay Chat System (RRCS).
